apiVersion: v1
kind: Secret
metadata:
  name: ch-custom-auth
  namespace: clickhouse
type: Opaque
stringData:
  username: admin
  password: clickhouse123
---
apiVersion: kubedb.com/v1alpha2
kind: ClickHouse
metadata:
  name: ch-cluster
  namespace: clickhouse
spec:
  version: "25.7.1"

  replicas: 1

  authSecret:
    name: ch-custom-auth

  storageType: Durable
  storage:
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: kube-prom-stack
        interval: 30s
---
apiVersion: v1
kind: Service
metadata:
  name: ch-cluster-external
  namespace: clickhouse
  annotations:
    metallb.io/address-pool: sandbox
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: clickhouses.kubedb.com
    app.kubernetes.io/instance: ch-cluster
  ports:
    - name: http
      port: 8123
      targetPort: 8123
    - name: native
      port: 9000
      targetPort: 9000
---
apiVersion: autoscaling.kubedb.com/v1alpha1
kind: ClickHouseAutoscaler
metadata:
  name: clickhouse-autoscaler
  namespace: clickhouse
spec:
  databaseRef:
    name: ch-cluster
  compute:
    clickhouse:
      minAllowed:
        cpu: 1
        memory: 2Gi
      maxAllowed:
        cpu: 2
        memory: 4Gi
      trigger: "On"
      controlledResources:
        - cpu
        - memory
      containerControlledValues: RequestsAndLimits

  storage:
    clickhouse:
      expansionMode: Online
      trigger: "On"
      usageThreshold: 60
      scalingThreshold: 100
