apiVersion: v1
kind: Secret
metadata:
  name: kafka-custom-auth 
  namespace: kafka
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: admin123
---
apiVersion: kubedb.com/v1
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  version: "3.7.2"
  
  authSecret:
    name: kafka-custom-auth
    externallyManaged: true
  
  topology:
    controller:
      replicas: 1
      storage:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
    broker:
      replicas: 1
      storage:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        port: 9091
      serviceMonitor:
        labels:
          release: kube-prom-stack
        interval: 30s

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-external
  namespace: kafka
  annotations:
    metallb.io/address-pool: sandbox # Fixed annotation format
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: kafkas.kubedb.com
    app.kubernetes.io/instance: kafka-cluster
    kubedb.com/role: broker
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-controller-external
  namespace: kafka
  annotations:
    metallb.universe.tf/address-pool: sandbox
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: kafkas.kubedb.com
    app.kubernetes.io/instance: kafka-cluster
    kubedb.com/role: controller
  ports:
    - name: kafka-controller
      protocol: TCP
      port: 9093
      targetPort: 9093
---
apiVersion: autoscaling.kubedb.com/v1alpha1
kind: KafkaAutoscaler
metadata:
  name: kafka-autoscaler
  namespace: kafka
spec:
  databaseRef:
    name: kafka-cluster
  storage:
    broker:
      minAllowed:
        cpu: "1"
        memory: 1Gi
      maxAllowed:
        cpu: "2"
        memory: 4Gi
      trigger: "On"
      controlledResources:
        - cpu
        - memory
      containerControlledValues: RequestsAndLimits

  storage:
    broker:
      expansionMode: Online
      trigger: "On"
      usageThreshold: 60
      scalingThreshold: 100
    controller:
      expansionMode: Online
      trigger: "On"
      usageThreshold: 60
      scalingThreshold: 100
