apiVersion: v1
kind: Secret
metadata:
  name: mysql-custom-auth  
  namespace: mysql
type: kubernetes.io/basic-auth
stringData:
  username: root
  password: mysql123
---
apiVersion: kubedb.com/v1
kind: MySQL
metadata:
  name: mysql-cluster
  namespace: mysql
spec:
  version: "8.0.35"
  replicas: 1

  authSecret:
    name: mysql-custom-auth
    externallyManaged: true

  storageType: Durable
  storage:
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi

  serviceTemplates:
    - alias: primary
      metadata:
        annotations:
          metallb.io/address-pool: newip
      spec:
        type: LoadBalancer
        ports:
          - name: mysql
            port: 3306
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        port: 9104
      serviceMonitor:
        labels:
          release: kube-prom-stack
        interval: 30s      
---
apiVersion: autoscaling.kubedb.com/v1alpha1
kind: MySQLAutoscaler
metadata:
  name: mysql-autoscaler
  namespace: mysql
spec:
  databaseRef:
    name: mysql-cluster

  compute:
    mysql:
      minAllowed:
        cpu: 400m
        memory: 400Mi
      maxAllowed:
        cpu: "1"
        memory: 1Gi
      trigger: "On"
      controlledResources:
        - cpu
        - memory
      containerControlledValues: RequestsAndLimits

  storage:
    mysql:
      expansionMode: Online
      trigger: "On"
      usageThreshold: 70
      scalingThreshold: 60  
